### ISSUE TITLE
Arguments in main parser not showing in subparser

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#10]
When write `python -fn [...] clumpr -h`. The parser does not show the `-fn [...]` argument as required argument.

**Comment by wutron** [comment]
I recommend that you use [argparse](https://docs.python.org/3/library/argparse.html)'s subcommands.  It will be simplify your main executable script, and make it easier to update commands or add new commands in the future.  Let me know if you need an example.

It might also be bad form to allow named arguments (`-fn`) before an unnamed argument (the command).  You might put common arguments (and, if you choose, your own formatter for displaying help) in a folder specifically for parsing, e.g. `parser.common` and `parser.formatter`.

**Comment by ssantichaivekin** [comment]
I will look into it when I have time. Feel free to modify the parser code too if you want :).

**Comment by ssantichaivekin** [comment]
Resolved in https://github.com/ssantichaivekin/empress/pull/123 . The filenames are now required arguments and are displayed correctly.
