### ISSUE TITLE
p-value histogram button not activated

### ISSUE THREAD

**Issue by rlhadas** [ssantichaivekin/eMPRess#131]
In the current master branch in the GUI the p-value histogram button does not appear to be activated.  It is grayed out even after loading in files and performing reconciliation.  Let's also be sure that when it is activated, in line 155 of empress/__init__.py, we use a default of 100 for num_trials (rather than the current value of 50).

**Comment by Qing-Yang-1211** [comment]
Done in this pull request: https://github.com/ssantichaivekin/eMPRess/pull/126

**Comment by Qing-Yang-1211** [comment]
> Done in this pull request: #126

@ssantichaivekin

**Comment by ssantichaivekin** [comment]
Will create a pull request for changing 50 -> 100 samples.
