### ISSUE TITLE
Add all files option to select host/parasite/mapping dropdown

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#137]
It seems that the list of filters are showing correctly in newer versions of tcl/tk. Might be a good idea to allow the "All files" option (represented as `("All files", "*")`) in the gui in case the user has a file that is formatted correctly bas has an extension that does not match that of empress.

<img width="789" alt="Screen Shot 2020-07-14 at 3 51 00 PM" src="https://user-images.githubusercontent.com/19219105/87485511-d46c2680-c5ed-11ea-9f5f-06f944bb8ea1.png">

**Comment by Qing-Yang-1211** [comment]
As you have mentioned in Slack, it would be nice to add an option to select all files, in case the users have the newick file or mapping file in the correct format but with incorrect file name extension. Yes, we can add that, but the user won't be able to switch from ("Newick Trees", "*.nwk .newick .tree") to ("All files", ".").

**Comment by ssantichaivekin** [comment]
Could we look at this together through zoom?

**Comment by Qing-Yang-1211** [comment]
Sure! How about now..?

**Comment by ssantichaivekin** [comment]
I wasn't able to switch from Newick trees to all files either. The options got grayed out similar to the issue described here: https://stackoverflow.com/questions/58799432/macos-tkinter-how-does-filetypes-of-askopenfilename-work . I have added the bounty to the stackoverflow question to draw more attention to the question, but I think this is a macOS bug. The code works fine on linux.
