### ISSUE TITLE
Investigate the version of tcl/tk that produces the correct file filter box

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#138]
My filter box (running tcl/tk 8.5.9):

<img width="800" alt="Screen Shot 2020-07-14 at 4 27 45 PM" src="https://user-images.githubusercontent.com/19219105/87485985-fc0fbe80-c5ee-11ea-8bfb-c2a7e8d3595e.png">

Qing's filter box:

<img width="789" alt="Screen Shot 2020-07-14 at 3 51 00 PM" src="https://user-images.githubusercontent.com/19219105/87485987-fe721880-c5ee-11ea-924f-9f1b3c4a5c78.png">

See how to look at the tcl/tk version:
https://stackoverflow.com/questions/35999344/how-to-determine-what-version-of-python3-tkinter-is-installed-on-my-linux-machin
```python
import tkinter
root = tkinter.Tk()
print(root.tk.call("info", "patchlevel"))
root.destroy()
```

**Comment by Qing-Yang-1211** [comment]
As you have mentioned in Slack, it would be nice to add an option to select all files, in case the users have the newick file or mapping file in the correct format but with incorrect file name extension. Yes, we can add that, but the user won't be able to switch from ("Newick Trees", "*.nwk *.newick *.tree") to ("All files", "*.*").

**Comment by Qing-Yang-1211** [comment]
My tkinter version is 8.6.8.

**Comment by ssantichaivekin** [comment]
When I use 8.6.8, the filter shows up on my computer too. Still, we cannot select the filters even in 8.6.8 -- see #137 .
