### ISSUE TITLE
Zooming in a matplotlib window fails after changing boolean options

### ISSUE THREAD

**Issue by rlhadas** [ssantichaivekin/empress#141]
When I view a reconciliation, it shows up great.  But, after I click on a button to either hide the internal node names or the frequencies, the zoom feature no longer works.  It may be that other matplotlib functions also get disabled by doing this.  Could you please check and also see if there is a way to fix this?

**Comment by rlhadas** [comment]
Some matplotlib features still work, such as saving the image.

**Comment by ssantichaivekin** [comment]
Although it seems like saving is working correctly, it is not. The image that is being saved is the image before clicking on the button. It seems like the buttons are still connected to the old figure even when we already change it to a new one.
