### ISSUE TITLE
HistogramDisplay incorrect number of MPR pairs exponent

### ISSUE THREAD

**Issue by rlhadas** [ssantichaivekin/eMPRess#19]
The y-axis of the histogram is not correct.  (It worked fine under Python 2, but seems to have broken in the move to Python 3.). The number of MPRs is 10^x where x is an exponent that is now always showing up as 0.  The problem appears to be in the way that exponent_text is extracted at line 40.

**Comment by ssantichaivekin** [comment]
Steps to reproduce:
Create a file named `test-size20-no22.newick` with the text:
```
(m1,(m3,(m5,(m7,(((m11,m12)m10,(m14,(m16,m17)m15)m13)m9,(((m43,m44)m42,(m46,(m48,m49)m47)m45)m41,(m73,(m75,((m78,m79)m77,(m81,m82)m80)m76)m74)m72)m40)m8)m6)m4)m2)m0;
(n1,(n3,(n5,(n7,(n9,(n11,(n13,(n15,(n17,(n19,(n21,(n23,(n25,(n27,(n29,(n31,(n33,(n35,(n37,n38)n36)n34)n32)n30)n28)n26)n24)n22)n20)n18)n16)n14)n12)n10)n8)n6)n4)n2)n0;
n1:m12
n3:m81
n5:m82
n7:m1
n9:m7
n11:m73
n13:m16
n15:m78
n17:m49
n19:m5
n21:m3
n23:m46
n25:m75
n27:m14
n29:m79
n31:m48
n33:m43
n35:m44
n37:m11
n38:m17
```
Then run `python empress.py -fn examples/test-size20-no22.newick histogram --histogram output.pdf`. The output pdf has incorrect exponent on the left.

<img width="558" alt="Screen Shot 2020-05-20 at 12 48 46 PM" src="https://user-images.githubusercontent.com/19219105/82490966-df488600-9a98-11ea-8ad0-9eb564884585.png">

**Comment by ssantichaivekin** [comment]
Prof Ran says the error is probably in `clumpr/HistogramDisplay.py`.
