### ISSUE TITLE
.zip on GitHub

### ISSUE THREAD

**Issue by andersonbrito** [ssantichaivekin/empress#226]
Hi,

Could you please make the installation files (.zip) available for download here on GitHub?

On Google Drive I'm getting this message, and the download button is not working.

> Google Drive can't scan this file for viruses.
> macos_empress_app.zip (38M) is too large for Google to scan for viruses. Would you still like to download this file?

Thank you.

**Comment by ssantichaivekin** [comment]
Hi Anderson, thank you for using empress. I just uploaded the executable applications to Github. Here's the download link: https://github.com/ssantichaivekin/empress/releases

I will notify @rlhadas, the maintainer of the empress website to update the website to use this link.
