### ISSUE TITLE
Add an option to close legend in matplotlib reconciliation window

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#238]
Reconciliation window legend can obstruct the reconciliation image as shown below:

<img width="498" alt="Screen Shot 2021-06-11 at 10 54 37 PM" src="https://user-images.githubusercontent.com/19219105/121714994-9bdc1200-cb08-11eb-8e39-c752621a279a.png">

Suggested Fix:

Instead of showing the legend on top of the reconciliation, add a button that shows the legend on a new window.

<img width="601" alt="Screen Shot 2021-06-11 at 10 57 43 PM" src="https://user-images.githubusercontent.com/19219105/121715003-9e3e6c00-cb08-11eb-9ec9-04c42efe7c39.png">

**Comment by rlhadas** [comment]
This will be a wonderful feature!
