### ISSUE TITLE
Add an option to increase/decrease font size in tanglegram and reconciliation window

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#239]
Because node font sizes are often too large or too small.

<img width="400" alt="Screen Shot 2021-06-11 at 11 01 30 PM" src="https://user-images.githubusercontent.com/19219105/121716348-1e190600-cb0a-11eb-922b-99dedcf60b6a.png">
<img width="400" alt="Screen Shot 2021-06-11 at 11 06 33 PM" src="https://user-images.githubusercontent.com/19219105/121716403-2ec97c00-cb0a-11eb-8bb1-8d8cbf025ac2.png">

**Comment by rlhadas** [comment]
This will be a very helpful and useful feature!  Thanks~
