### ISSUE TITLE
Naming issues with xscape and clumpr

### ISSUE THREAD

**Issue by rlhadas** [ssantichaivekin/eMPRess#27]
We currently split the codebase into xscape and clumpr.  clumpr is probably not the right name for this, since it refers to "CLUstering MPRs", but what's currently in the clumpr module is actually  more than this; we have reconciliation, histograms, and clustering.  Coming soon will be statistical testing and visualization of MPRs.  So, perhaps xscape is really "pareto" and the rest of the code based is "fixedcost".

**Comment by ssantichaivekin** [comment]
I think we should drop the terms `clumpr` and `xscape` from this repository.

**Comment by rlhadas** [comment]
Agree.

**Comment by wutron** [comment]
I recommend putting all the libraries in some folder that gets installed onto PYTHONPATH.  Each file is responsible for one functionality (e.g. reconcile, costscape, cluster, etc).

**Comment by ssantichaivekin** [comment]
We removed the term clumpr and we are still using the term xscape for now. see #82 .
