### ISSUE TITLE
Tanglegram library in codebase but not used

### ISSUE THREAD

**Issue by maxoja** [ssantichaivekin/eMPRess#55]
- Check if `tanglegram-rls` is used. If not, delete `/tanglegram-rls`
- Check if any of items in Pipfile wasn't used

**Comment by ssantichaivekin** [comment]
All the things in Pipfile are used. I think `pydot` is kind of tricky. It is never imported explicitly, but the line `pydotDtlGraph = nx.drawing.nx_pydot.to_pydot(nxDtlGraph)` will break without it.
