### ISSUE TITLE
[Failed Test] Or perhaps wrong test

### ISSUE THREAD

**Issue by maxoja** [ssantichaivekin/eMPRess#59]
when running
`python -m unittest discover "./test"`

It gives the following error at .\test\test_empress_wrapper.py line 30
`AttributeError: 'NoneType' object has no attribute 'draw_to_file'`

**Comment by ssantichaivekin** [comment]
Ah this is my bad. I'm planning to convert the file to a test but it's still just an example on how the interface is supposed to be used.

**Comment by ssantichaivekin** [comment]
I will convert it to a test soon.

**Comment by ssantichaivekin** [comment]
Duplicate of #32 .

**Comment by maxoja** [comment]
Awesome, thanks!
