### ISSUE TITLE
Refactor empress to use absolute import path

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/eMPRess#6]
Currently, we are importing files(modules) in a non-standard way. We want to either use [absolute import or relative import](https://realpython.com/absolute-vs-relative-python-imports/). According to Google Python style guide, [absolute import is preferred](https://realpython.com/absolute-vs-relative-python-imports/). This change involves modifying **all** import lines in the codebase.

Note, we have decided to use absolute import.

Examples:

Before (in `clumpr/DTLReconGraph.py`):
```python
import Greedy
import newickFormatReader
import ReconcileMainInput
```
After absolute import:
```python
from clumpr import Greedy
from clumpr import newickFormatReader
from clumpr import ReconcileMainInput
```

Before (in `xcape/costcape.py`):
```python
try:
    import xscape
except ImportError:
    import sys
    from os.path import realpath, dirname, join
    sys.path.append("../python")
    import xscape
from xscape.commonAnalytic import *
from xscape.CostVector import *
from xscape import getInput
```
After absolute import:
```python
from xscape.python.xscape.commonAnalytic import *
from xscape.python.xscape.costVector import *
from xscape.python.xscape import getInput
```

Pros of using either absolute import or relative import:
- Allow editors such as vscode and pycharm to see and analyze imports

Pros of using absolute import:
- Easier to write unit tests
- Easier to read than relative import
- Easier to refactor if we change the locations of folders
- Consistent with Google style guide

Cons of using absolute import:
- We will not be able to run files in subdirectories independently. `python clumpr/DTLReconGraph.py trees.newick 1 2 1` will no longer work (see comment). We will have to write `python -m clumpr.DTLReconGraph trees.newick 1 2 1` instead for the same functionality. This is less intuitive for newcomers. However, I think we should remove the option to run each file on its own anyway, so I think this is warranted

Cons of not switching:
- Hard to navigate code in editors because `ctrl` + `click` does not work
- Hard to write unit tests in a different folder far from the folder being tested
- Hard to use tools that analyze the relationships between different files in the code

**Comment by ssantichaivekin** [comment]
The reason absolute import will break running the script as `python clumpr/DTLReconGraph.py trees.newick 1 2 1` is because when python starts, it sets its current directory to the directory of the script. Which is in `clumpr`. Python does not go to the outer directory to check for import paths, so the import will fail. Running python as module `python -m clumpr.DTLReconGraph trees.newick 1 2 1` fixes the problem.

**Comment by wutron** [comment]
Absolute imports are the way to go.  But don't import wildcards.  That makes it a pain later to figure out what functionality you are using from what module.  Better to be explicit, e.g. prefer from `module import file` over `from module import file as *` or `import module.file as *`.

**Comment by ssantichaivekin** [comment]
I agree that we should not import wildcards.
