### ISSUE TITLE
Inaccurate help documentation in costscape 

### ISSUE THREAD

**Issue by ssantichaivekin** [ssantichaivekin/empress#9]
When running `python eMPRess costscape -h`, the description shown in inaccurate:

- [x] There are two optional conflicting arguments `switch` and `transfer`. `switch` should be changed to `loss`. Note that the cost of duplication to 1 (resolved in #35)
- [ ] The command line should display the default value

**Comment by rlhadas** [comment]
The first of these two issues is resolved.  I don't think that the second one has been addressed.

**Comment by wutron** [comment]
I think we are making loss the unit-less event now, so you should allow the user to input dups and transfer (or switch) ranges.

**Comment by ssantichaivekin** [comment]
Yes. The two arguments are now duplication cost and transfer cost.

**Comment by ssantichaivekin** [comment]
Resolved in https://github.com/ssantichaivekin/empress/pull/123 .
